steps:
  # Build dify-api image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-docker.pkg.dev/quri-artifact/quri-image/langgenius/dify-api:latest', '-f', './api/Dockerfile', '.' ]

  # Build dify-web image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-docker.pkg.dev/quri-artifact/quri-image/langgenius/dify-web:latest', '-f', './web/Dockerfile', '.' ]

  # Pull necessary images from Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'nginx:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'langgenius/dify-sandbox:latest']

  # Tag the pulled images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'nginx:latest', 'asia-docker.pkg.dev/quri-artifact/quri-image/nginx:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'langgenius/dify-sandbox:0.2.1', 'asia-docker.pkg.dev/quri-artifact/quri-image/langgenius/dify-sandbox:0.2.1']

  # Push all images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/quri-artifact/quri-image/langgenius/dify-api:0.6.9']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/quri-artifact/quri-image/langgenius/dify-web:0.6.9']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/quri-artifact/quri-image/nginx:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/quri-artifact/quri-image/langgenius/dify-sandbox:0.2.1']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'services', 'replace', 'dify-qunasys.yaml']
    env:
      - 'CLOUDSDK_CORE_PROJECT=277054394945'

